[package]
name = "state_machines_macros"
version = "0.1.0"
authors = ["Chris Hawblitzel <Chris.Hawblitzel@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = { version = "0.15", features = ["full"] }
quote = "0.6"
smir = { path = "../smir" }

[lib]
proc-macro = true
